# Generated by Django 2.1.7 on 2019-02-20 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0005_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('categories', models.ManyToManyField(related_name='categories', to='orgs.Detail')),
            ],
        ),
    ]
