# Generated by Django 2.1.7 on 2019-02-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0006_subgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('sub_Group', models.ManyToManyField(related_name='sub_Group', to='orgs.Detail')),
            ],
        ),
    ]
