# Generated by Django 2.1.7 on 2019-02-22 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0008_subproperty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('body', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='sub_Group',
        ),
        migrations.RemoveField(
            model_name='subproperty',
            name='group',
        ),
        migrations.AddField(
            model_name='group',
            name='sub_Groups',
            field=models.ManyToManyField(related_name='sub_Groups', to='orgs.SubGroup'),
        ),
        migrations.AddField(
            model_name='subproperty',
            name='groups',
            field=models.ManyToManyField(related_name='groups', to='orgs.Group'),
        ),
        migrations.AlterField(
            model_name='category',
            name='items',
            field=models.ManyToManyField(related_name='items', to='orgs.Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='features',
            field=models.ManyToManyField(related_name='features', to='orgs.Feature'),
        ),
        migrations.AlterField(
            model_name='subgroup',
            name='categories',
            field=models.ManyToManyField(related_name='categories', to='orgs.Category'),
        ),
        migrations.AddField(
            model_name='property',
            name='sub_Properties',
            field=models.ManyToManyField(related_name='sub_Properties', to='orgs.SubProperty'),
        ),
        migrations.AddField(
            model_name='organization',
            name='properties',
            field=models.ManyToManyField(related_name='properties', to='orgs.Property'),
        ),
    ]
